version: "3.1"

services:
  db-gestionstock-postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestion_stock
    ports:
      - "5432:5432"
    volumes:
      - ./volumes:/var/lib/postgresql/data